---
name: 'publish-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:
    name: 'Publish Release'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Sources'
        uses: actions/checkout@v2

      - name: 'Prepare NodeJS Installation'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: 'Install NodeJS Depedencies'
        run: npm install

      - name: 'Build Module'
        run: npm run build

      - name: 'Package Module'
        run: npm run zip

      - name: 'Create Github Release'
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            module.zip
            module/module.json